BLOCK_SIZE = 24;
GAME_SIZE = 27;

FPS = 45;
FRAME_TIME = Math.round(1000 / FPS);

DEATH_BY_WALL	= 0
DEATH_BY_WORM	= 1

MOVE_LEFT		= 1;
MOVE_RIGHT		= 2;
MOVE_UP			= 4;
MOVE_DOWN		= 8;
DROP_BOMB		= 16;
OPEN_MENU		= 32;
ENTER			= 64;
ACTIVATE_BOOST  = 128;

BUTTON_MAP = {
	37: MOVE_LEFT,
	65: MOVE_LEFT,
	39: MOVE_RIGHT,
	68: MOVE_RIGHT,
	38: MOVE_UP,
	87: MOVE_UP,
	40: MOVE_DOWN,
	83: MOVE_DOWN,
	66: ACTIVATE_BOOST,
	27: OPEN_MENU,
	13: ENTER,
	32: DROP_BOMB
};

MOVE_LEFT_DOWN		= MOVE_LEFT;
MOVE_RIGHT_DOWN		= MOVE_RIGHT;
MOVE_UP_DOWN		= MOVE_UP;
MOVE_DOWN_DOWN		= MOVE_DOWN;
DROP_BOMB_DOWN		= DROP_BOMB;
OPEN_MENU_DOWN		= OPEN_MENU;
ENTER_DOWN			= ENTER;
ACTIVATE_BOOST_DOWN	= ACTIVATE_BOOST;

MOVE_LEFT_UP		= -MOVE_LEFT;
MOVE_RIGHT_UP		= -MOVE_RIGHT;
MOVE_UP_UP			= -MOVE_UP;
MOVE_DOWN_UP		= -MOVE_DOWN;
DROP_BOMB_UP		= -DROP_BOMB;
OPEN_MENU_UP		= -OPEN_MENU;
ENTER_UP			= -ENTER;
ACTIVATE_BOOST_UP	= -ACTIVATE_BOOST;